services:
  - type: web
    name: employee-management-system
    env: ruby
     buildCommand: |
      bundle install && 
      bundle exec rails db:migrate && 
      bundle exec rails db:seed RAILS_ENV=production && 
      bundle exec rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase: employee-management-system-db
databases:
  - name: employee-management-system-db
    plan: free
