default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: employee_management_system_development
  host: localhost
  port: 5432
  username: postgres
  password: root

test:
  <<: *default
  database: employee_management_system_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['render_employee_management'] %>
  username: <%= ENV['render_employee_management_user'] %>
  password: <%= ENV['9d01pUvacGkqd4q6Fooxx5jurcT3ycH2'] %>
  host: <%= ENV['dpg-ctuj3qdds78s73fook3g-a'] %>
  url: <%= ENV['DATABASE_URL'] %>
  port: 5432
  
