default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: employee_management_system_development
  host: localhost
  port: 5432
  username: postgres
  password: root

test:
  <<: *default
  database: employee_management_system_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['render_employee_management'] %>
  username: <%= ENV['render_employee_management_user'] %>
  password: <%= ENV['render_employee_management_password'] %>
  host: <%= ENV['RENDER_DB_HOST'] || 'localhost' %>
  url: <%= ENV['DATABASE_URL'] %>
  port: 5432

cable:
  <<: *default
  database: <%= ENV['RENDER_CABLE_DB'] %>
  username: <%= ENV['RENDER_DB_USER'] %>
  password: <%= ENV['RENDER_DB_PASSWORD'] %>
  host: <%= ENV['RENDER_DB_HOST'] || 'localhost' %>
  port: 5432
  

  
